workspace = { members = ["examples/hello_world", "examples/playground", "examples/primitives"] }

[package]
name = "rust-pro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
